<a href="https://colab.research.google.com/github/SainathJeevangi/SainathJeevangi.github.io/blob/main/AQT_Exercice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# Example for a Schmidt decomposition, using the QuTiP package
# Advanced Quantum Theory Course, SS 2026
# Jörg Evers
#
import  qutip as qt
import numpy as np

# define the basis states of the two qubits
spin1_down = qt.basis(2,0)
spin1_up = qt.basis(2,1)

spin2_down = qt.basis(2,0)
spin2_up = qt.basis(2,1)

# define the state as in the problem sheet
# use the tensor product to combine two qubits
psi = 1/np.sqrt(20) * (   3 * qt.tensor(spin1_up,    spin2_up  ) \
                        - 3 * qt.tensor(spin1_down,  spin2_down) \
                        + 1 * qt.tensor(spin1_up,    spin2_down) \
                        - 1 * qt.tensor(spin1_down,  spin2_up) )


# print wave function
print("the wave function is")
print(psi, "\n\n")

# calculate density matrix as |psi><psi|
# here the "*" is the outer product since it is applied between ket and bra
rho = psi * psi.dag()

print("the density matrix is")
print(rho,  "\n\n")

# - calculate the partial trace over the second qubit to get rho_1
# - this leaves the subspaces which are *not* passed as argument,
#   i.e., here the subspace 1 belonging to the second qubit is traced out
#   while the subspace 0 belonging to the first qubit is preserved
rho_1 = rho.ptrace(0)
print("the partial trace over qubit 2 gives rho_1 as")
print(rho_1, "\n\n")

# calculate the partial trace over the first qubit to get rho_2
rho_2 = rho.ptrace(1)
print("the partial trace over qubit 1 gives rho_2 as")
print(rho_2, "\n\n")


# - calculate the eigenvalues and eigenvectors of the reduced density matrices
# - note that the eigenstates are only defined up to an overall phase
# - it is important to calculate eigenvalues and eigenstates together, because
#   in a separate calculation, the computational tools sometimes mix their order
#   relative to each other
eigenvalues_1, eigenstates_1 =  rho_1.eigenstates()
eigenvalues_2, eigenstates_2 =  rho_2.eigenstates()

print(f"the eigenvalues of rho_1 are {eigenvalues_1} and the ones of rho_2 are {eigenvalues_2}\n\n")


# - there are two non-zero eigenvalues, hence the Schmidt decomposition has two parts.
# - Up to the prefactors, the two parts are given by
schmidt_1 = qt.tensor( eigenstates_1[0], eigenstates_2[0])
schmidt_2 = qt.tensor( eigenstates_1[1], eigenstates_2[1])

# get the prefactors of the two parts by projecting out the two orthogonal
# Schmidt "vectors" from the original state
prefactor_1 = schmidt_1.dag() * psi
prefactor_2 = schmidt_2.dag() * psi


# these agree to the square root of the eigenvalues as derived in the course,
# however only up to a phase coming from the (undefined) overall phase of the eigenvectors
print(f"the first addend in the Schmidt decomposition has prefactor {prefactor_1:.5f}")
print(f"the square root of the corresponding eigenvalue is {np.sqrt(eigenvalues_1[0]):.5f}\n\n")
print(f"the second addend in the Schmidt decomposition  has prefactor {prefactor_2:.5f}")
print(f"the square root of the corresponding eigenvalue is {np.sqrt(eigenvalues_1[1]):.5f}\n\n")


# the schmidt decomposition now is
# psi = sum_i (prefactor_i * schmidt_1)
psi_schmidt = prefactor_1 * schmidt_1 + prefactor_2 * schmidt_2
scalar_product = psi_schmidt.dag() * psi
print(f"test the decomposition using the state overlap: <schmidt decomposition|psi> = {scalar_product:.5f}")

# for this decomposition the overall phase of the eigenvectors must be
# chosen correctly, otherwise the decomposition does not agree to the origiinal
# psi


# we can also compare to the result from the problem sheet
psi_solution  =  1/2*np.sqrt(1/5) * qt.tensor(spin1_up+spin1_down, spin2_up-spin2_down)  \
      + 1/2*np.sqrt(4/5) * qt.tensor(spin1_up-spin1_down, spin2_up+spin2_down)
scalar_product = psi_solution.dag() * psi
print(f"test the decomposition using the state overlap: <result homework|psi> = {scalar_product:.5f}")

the wave function is
Quantum object: dims=[[2, 2], [1]], shape=(4, 1), type='ket', dtype=Dense
Qobj data =
[[-0.67082039]
 [-0.2236068 ]
 [ 0.2236068 ]
 [ 0.67082039]] 


the density matrix is
Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.45  0.15 -0.15 -0.45]
 [ 0.15  0.05 -0.05 -0.15]
 [-0.15 -0.05  0.05  0.15]
 [-0.45 -0.15  0.15  0.45]] 


the partial trace over qubit 2 gives rho_1 as
Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[ 0.5 -0.3]
 [-0.3  0.5]] 


the partial trace over qubit 1 gives rho_2 as
Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.5 0.3]
 [0.3 0.5]] 


the eigenvalues of rho_1 are [0.2 0.8] and the ones of rho_2 are [0.2 0.8]


the first addend in the Schmidt decomposition has prefactor -0.44721+0.00000j
the square root of the corresponding eigenvalue is 0.44721


the second addend in the Schmidt d